package online.pasaka.Kafka.models

enum class NotificationType {
    BUY_ORDER_HAS_BEEN_PLACED,
    BUYER_HAS_TRANSFERRED_FUNDS,
    BUY_ORDER_COMPLETED,
    BUY_ORDER_EXPIRED,
    BUY_ORDER_CANCELLED,
    SELL_ORDER_HAS_BEEN_PLACED,
    SELL_ORDER_CANCELLED,
    SELL_ORDER_COMPLETED,
    SELL_ORDER_EXPIRED,
    MERCHANT_HAS_TRANSFERRED_FUNDS
}